language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.2.2
  - jruby
  - ruby-head
  - jruby-head
  - ree
  - rbx
branches:
  only:
    - master